name: Build QMK Firmware & Release

on:
  push:
    branches: [ master, main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli

    strategy:
      fail-fast: false
      matrix:
        keymap: [default, via]

    steps:
    - name: Checkout QMK Firmware
      uses: actions/checkout@v4
      with:
        repository: qmk/qmk_firmware
        submodules: recursive
        path: qmk_firmware

    - name: Checkout RK75 Repository
      uses: actions/checkout@v4
      with:
        path: rk75

    - name: Copy RK75 into QMK
      run: |
        rm -rf qmk_firmware/keyboards/rk/r75
        mkdir -p qmk_firmware/keyboards/rk/r75
        cp -r rk75/keyboard/rk/r75/* qmk_firmware/keyboards/rk/r75/

    - name: Build Keymap
      run: |
        cd qmk_firmware
        qmk compile -kb rk/r75 -km ${{ matrix.keymap }} || exit 1

    - name: Prepare Artifact
      run: |
        if [ "${{ matrix.keymap }}" == "default" ]; then
          TYPE="Default"
        else
          TYPE="Via"
        fi
        NEW_NAME="RK75_ISO_${{ github.ref_name }}_${TYPE}.bin"
        
        mkdir -p dist
        cp qmk_firmware/rk_r75_${{ matrix.keymap }}.bin dist/$NEW_NAME
        
        echo "âœ… Fichier prÃªt dans : dist/$NEW_NAME"

    - name: Archive Firmware
      uses: actions/upload-artifact@v4
      with:
        name: rk75-${{ matrix.keymap }}
        path: dist/*
        if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download All Artifacts Separately
        uses: actions/download-artifact@v4
        with:
          pattern: rk75-*
          path: temp_artifacts

      - name: Consolidate Files
        run: |
          mkdir final_firmware
          
          find temp_artifacts -name "*.bin" -exec cp {} final_firmware/ \;
          
          echo "ðŸ“‚ Contenu final (Preuve) :"
          ls -R final_firmware/

      - name: Create Release with GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: |
          gh release create "$TAG" \
            final_firmware/*.bin \
            --title "Release $TAG" \
            --generate-notes